windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAB38AAAPIAAAAAAAAAAAAAAd/AAADyAAAAAAAAAAAB4AAAAAAAAAA
    AAAAB38AAAPI
  tabs:
  - history:
    - active: true
      last_visited: '2025-05-15T19:00:10'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Google
      url: https://www.google.com/
      zoom: 1.5
  - active: true
    history:
    - active: true
      last_visited: '2025-05-15T19:00:10'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: qutebrowser quickstart | qutebrowser
      url: https://www.qutebrowser.org/quickstart.html
      zoom: 1.5
