# ~/.config/sworkstyle/config.toml

fallback = ''
separator = ' '

[matching]
# Add this new rule for .norg files.
# It will match any window title containing ".norg".
# Replace '' with your preferred norg icon.
'/.*\.norg.*/' = ''

# --- Existing Rules ---

# Code Editor Icon (This rule will now be a fallback for non-norg files)
'/Nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''

# Corrected name for Wezterm (This is an exact match for the app_id, 
# it will be overridden by a title match like the one for Neovim)
'org.wezfurlong.wezterm' = ''
'kitty' = ''

# Browser Icon
'org.qutebrowser.qutebrowser' = ''

# File Manager Icons
'thunar' = ''
'nautilus' = ''

# Media Icons
'mpv' = ''
'vlc' = ''
'swappy' = ''

# Other
'anki' = ''
'libreoffice-startcenter' = ''
'soffice' = ''
'libreoffice-writer' = ''
'libreoffice-base' = ''
'libreoffice-calc' = ''
'libreoffice-draw' = ''
'libreoffice-impress' = ''
'libreoffice-math' = ''
'org.pwmt.zathura' = '󰈦'
